# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首頁
    url: '#about'
    weight: 10
  - name: 部落格
    url: 'blog'
  - name: 出版物
    url: 'publication'
    weight: 50
  - name: 演講與訪談
    url: 'talks'
    weight: 50
#  - name: 資源
#    url: 'resource'
#    weight: 50
#  - name: 專題計畫
#    url: '#projects'
#    weight: 30
#  - name: 演講
#    url: '#talks'
#    weight: 40

  - name: 聯絡方式
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 70
